### ISSUE TITLE
RuntimeError: min(): Expected reduction dim to be specified for input.numel() == 0

### ISSUE THREAD

**Issue by dr-costas** [fakufaku/fast_bss_eval#17]
Hi, 

I'm trying to use the `torch.bss_eval_sources` and I'm getting the error:

```
fast_bss_eval/torch/helpers.py", line 142, in _linear_sum_assignment_with_inf 
  m = values.min()
RuntimeError: min(): Expected reduction dim to be specified for input.numel() == 0. Specify the reduction dim with the 'dim' argument.
```

Any pointers on that?

**Comment by fakufaku** [comment]
Hi @dr-costas Did you figure it out ?

**Comment by dr-costas** [comment]
Hi, 

Well, no, but I side-stepped it. The problem, n my case, occurs when trying to calculate permutations, which I really don't need. So, I don't calculate permutations and all are good :)

**Comment by fakufaku** [comment]
Ok 😄 
I think this may happen when one of the references is all zeros, or if you have some nan or inf in your signal.
